-- Add fileds needed in contest permission check
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `uestcoj`.`contest` 
  ADD COLUMN `password` VARCHAR(40) NULL DEFAULT NULL  AFTER `OPTLOCK` , 
  ADD COLUMN `parentId` INT(11) NULL DEFAULT NULL  AFTER `password` , 
  ADD CONSTRAINT `FK_parentId_on_contest_idx`
    FOREIGN KEY (`parentId` )
    REFERENCES `uestcoj`.`contest` (`contestId` )
    ON DELETE CASCADE
    ON UPDATE CASCADE, 
  ADD INDEX `FK_parentId_on_contest_idx_idx` (`parentId` ASC) ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
