$ = jQuery;
$ ->
  initUI()
  initLayout()
  initStatusList()
  initUserList()
  initUser()
  initUserActivate()
  initProblemList()
  initProblemPage()
  initProblemEditor()
  initProblemDataEditor()
  initContestList()
  initContestPage()
  initArticleEditor()
  initArticleList()
  render()